### PR TITLE
Add first version of bot working on variation histories

### PR DESCRIPTION
**Pull request by wm75**

### CODE REVIEW

**Comment by simonbray** [comment]
@wm75 I made a couple of very small changes - if you agree, feel free to merge

**Comment by wm75** [comment]
@simonbray I decided to make the script a lot more flexible:
find_datasets.py can now:
- find histories that have specified tags and contain one or more datasets specified by name
- it can return information about the histories and their datasets in arbitrary formats if you use its `--from-template` option.

I know this lacks commenting everywhere, but I hope you can figure things out from the cli help.
With this script we should be able to simplify parameter passing between steps in bash a lot.

**Comment by wm75** [comment]
Example usage:
`echo '{histories[0][name]} {datasets[0][id]} {datasets[1][id]}' | python find_datasets.py 'Final (SnpEff-) annotated variants' 'Preprocessing and mapping reports' -g 'https://usegalaxy.eu' -a API_KEY -n 1 --from-template`
=>
`COG-UK NT1660207V v2 0fad0ae1a3c7c213 11ac94870d0bb33a9262278c8dde2249`

or even:

`cat beacon_export-job.yml`
=>
```
Annotated list of variants:
  class: Collection
  galaxy_id: "{datasets[0][id]}"
Fully processed aligned reads:
  class: Collection
  galaxy_id: "{datasets[1][id]}"

```
`cat beacon_export-job.yml | python find_datasets.py 'Final (SnpEff-) annotated variants' 'Preprocessing and mapping reports' -g 'https://usegalaxy.eu' -a API_KEY -n 1 --from-template`
=>
```
Annotated list of variants:
  class: Collection
  galaxy_id: "0fad0ae1a3c7c213"
Fully processed aligned reads:
  class: Collection
  galaxy_id: "11ac94870d0bb33a9262278c8dde2249"
```

**Comment by simonbray** [comment]
Looks really nice!

**Review by simonbray — APPROVED** [review]

**Pull request merged**
